

services:
  - type: static
    name: techavinya
    env: node 
    buildCommand: npm run build 
    staticPublishPath: dist
    
    routes:
      - type: rewrite
        source: /.* 
        destination: /index.html
